# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SF-DDoketkurly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SF-DDoketkurly
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'Kingfisher', '~> 6.0'
  pod 'SwiftGen', '~> 6.0'

end
